
stages:
  - compile
  - deploy

before_script:
  - yarn install
  - tsc

build:
  stage: compile
  script: 
    - echo "testing"
  only:
    - master
    - tags
  tags:
    - windows
    - node
    - typescript
    - yarn

deploy_win:
  stage: deploy
  dependencies:
  - build
  script: 
    - npm prune --production
    - npm dedupe
    - npm run dist
  only:
    - tags
  tags:
    - windows
    - node
    - typescript
    - yarn
    - electron-builder