stages:
  - precompile
  - compile
  - pretest
  - test
  - predeploy
  - deploy

configure_packages:
  stage: precompile
  tags:
    - windows
    - node
    - yarn
  script:
    - yarn install
  cache:
    untracked: true

compile:
  stage: compile
  script:
    - tsc
  only:
    - master
    - tags
  tags:
    - windows
    - node
    - typescript
  cache:
    untracked: true

test:
  stage: test
  script:
    - echo "testing"
  only:
    - master
    - tags
  tags:
    - windows
    - node
  cache:
    untracked: true

predeploy_win:
  stage: predeploy
  script:
    - npm prune --production
    - npm dedupe
  only:
    - master
    - tags
  tags:
    - windows
    - node
    - npm
  cache:
    untracked: true

deploy_win:
  stage: deploy
  script:
    - npm run dist
  only:
    - master
    - tags
  tags:
    - windows
    - node
    - electron-builder
  artifacts:
    paths:
      - dist/*.exe
    when: on_success