
stages:
  - compile
  - deploy

.compile: &job_definition 
  script:
    - yarn install
    - tsc
  tags:
    - windows
    - node
    - typescript
    - yarn

build:
  <<: *job_definition
  stage: compile
  script: 
    - echo "testing"
  only:
    - master
    - tags

deploy_win:
  <<: *job_definition
  stage: deploy
  dependencies:
  - build
  script: 
    - npm prune --production
    - npm dedupe
    - npm run dist
  only:
    - tags
  tags:
    - electron-builder