
stages:
  - compile
  - deploy

before_script:
  - call yarn install
  - call tsc

build:
  stage: compile
  script: 
    - echo "testing"
  only:
    - master
    - tags
  tags:
    - windows
    - node
    - typescript
    - yarn

deploy_win:
  stage: deploy
  dependencies:
  - build
  script: 
    - call npm prune --production
    - call npm dedupe
    - call npm run dist
  only:
    - tags
  tags:
    - windows
    - node
    - typescript
    - yarn
    - electron-builder