
stages:
  - compile
  - deploy

before_script:
  - call yarn install

build:
  stage: compile
  script: 
    - call tsc
  only:
    - master
    - tags
  tags:
    - windows
    - node
    - typescript
    - yarn

deploy_win:
  stage: deploy
  dependencies:
  - build
  script: 
    - call tsc
    - call npm prune --production
    - call npm dedupe
    - call build -c.extraMetadata.version=%CI_COMMIT_TAG%
    - call deployo -u %DEPLOYMENT_SERVER% -r %DEPLOYO_PROJECT_NAME% -n %CI_COMMIT_TAG% -k %DEPLOYO_KEY% -f "%cd%\dist\file-watcher Setup %CI_COMMIT_TAG%.exe"
  only:
    - tags
  tags:
    - windows
    - node
    - typescript
    - yarn
    - electron-builder
    - deployo