
cache:
  paths:
  - node_modules/

stages:
  - compile
  - test
  - deploy

compile:
  stage: compile
  dependencies:
  - configure_packages
  before_script:
    - yarn install
  script:
    - tsc
  only:
    - master
    - tags
  tags:
    - windows
    - node
    - typescript
    - yarn

test:
  stage: test
  dependencies:
  - compile
  script:
    - echo "testing"
  only:
    - master
    - tags
  tags:
    - windows
    - node

deploy_win:
  stage: deploy
  dependencies:
  - compile
  before_script:
    - npm prune --production
    - npm dedupe
  script:
    - npm run dist
  only:
    - master
    - tags
  tags:
    - windows
    - node
    - electron-builder
  artifacts:
    paths:
      - dist/*.exe
    when: on_success