stages:
  - precompile
  - compile
  - pretest
  - test
  - predeploy
  - deploy

configure_npm_packages:
  stage: precompile
  tags:
    - windows
    - node
  script:
    - npm install

compile:
  stage: compile
  script:
    - tsc
  only:
    - master
    - tags
  tags:
    - windows
    - node

test:
  stage: test
  script:
    - echo "testing"
  only:
    - tags
  tags:
    - windows
    - node

predeploy_win:
  stage: predeploy
  script:
    - npm prune --production
    - npm dedupe
  only:
    - tags
  tags:
    - windows
    - node

deploy_win:
  stage: deploy
  script:
    - npm run dist
  only:
    - tags
  tags:
    - windows
    - node
  artifacts:
    paths:
      - dist/*.exe
    when: on_success