
stages:
  - compile
  - deploy

build:
  stage: compile
  before_script:
    - yarn install
  script:
    - tsc
    - echo "testing"
  only:
    - master
    - tags
  tags:
    - windows
    - node
    - typescript
    - yarn

deploy_win:
  stage: deploy
  dependencies:
  - build
  before_script:
    - yarn install
    - tsc
  script:
    - npm prune --production
    - npm dedupe
    - npm run dist
  only:
    - tags
  tags:
    - windows
    - node
    - electron-builder
    - typescript
    - yarn