
stages:
  - compile
  - deploy

before_script:
  - call yarn install

build:
  stage: compile
  script: 
    - call tsc
  only:
    - master
    - tags
  tags:
    - windows
    - node
    - typescript
    - yarn

deploy_win:
  stage: deploy
  dependencies:
  - build
  script: 
    - call tsc
    - call npm prune --production
    - call npm dedupe
    - call build -c.extraMetadata.version=%CI_COMMIT_TAG%
    - call deployo --url=http://c549nutclrdva.tlr.thomson.com:8999/repo/file-watcher/%CI_COMMIT_TAG% --key=%DEPLOYO_KEY% --file="%cd%\dist\file-watcher Setup %CI_COMMIT_TAG%.exe"
  only:
    - tags
  tags:
    - windows
    - node
    - typescript
    - yarn
    - electron-builder
    - deployo