stages:
  - precompile
  - compile
  - prebuild
  - build

configure_npm_packages:
  stage: precomile
  tags:
    - windows
    - node
  script:
    - npm install

compile_master:
  stage: compile
  script:
    - .\node_modules\.bin\tsc
  only:
    - master
  tags:
    - windows
    - node
  
compile_tags:
  stage: compile
  script:
    - .\node_modules\.bin\tsc
  only:
    - tags
  tags:
    - windows
    - node

prebuild_win:
  stage: prebuild
  script:
    - npm prune --production
    - npm dedupe
  only:
    - tags
  tags:
    - windows
    - node
  artifacts:
    paths:
      - dist/*.exe
    when: on_success

build_win:
  stage: build
  script:
    - npm run dist
  only:
    - tags
  tags:
    - windows
    - node
  artifacts:
    paths:
      - dist/*.exe
    when:
      - on_success